### ISSUE TITLE
Memory Managers (tracking)

### ISSUE THREAD

**Issue by Eein** [Eein/sea-of-stars-tas#16]
- [x] TitleSequenceManager
- [x] Player Party Manager
  - [x] unwrap the class/profile/module/singlton on `update()`
  - [x] movement state
  - [ ] read leader character https://github.com/shenef/SoS-TAS/blob/speedrun-update/engine/seq/routing.py#L19-L30
  - [ ] read current_party -  used in Inventory
  - [ ] look for climbing/falling/etc state 
- [x] Shop Manager
- [ ] Combat Manager

**Comment by Eein** [comment]
![image](https://github.com/user-attachments/assets/abeea05d-64b6-4eb1-a4f8-d8b458e15dde)

**Comment by Eein** [comment]
Closing this tracking issue in favor of need-it-now tickets.
