### ISSUE TITLE
Add Windows Controller Support (tracking)

### ISSUE THREAD

**Issue by Eein** [Eein/sea-of-stars-tas#7]
may need to require ViGEmBus again for windows
https://docs.rs/vigem-client/latest/vigem_client/ then this

- [x] Create a windows mapper #15 
- [x] Add a joystick trait and implement for each joystick type and condense common code #24 
- [x] Add button press/release functions to common #24 
- [x] Add Triggers code #24

**Comment by Eein** [comment]
Just a note, when running tests i did feel like the controller didn't work properly so we'll have to visit this further later if it does become an issue
 
Edit: this was because tests were paralell and opening new joysticks on new ports
